// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inference/v1/conf.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Server *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Optional managed Governance command/refund wiring. When configured, both
	// inbound and outbound identities are required; no plaintext fallback.
	ManagedGpu    *ManagedGPU `protobuf:"bytes,2,opt,name=managed_gpu,json=managedGpu,proto3" json:"managed_gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_inference_v1_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_inference_v1_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetManagedGpu() *ManagedGPU {
	if x != nil {
		return x.ManagedGpu
	}
	return nil
}

type ManagedGPU struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Receiver *ManagedGPU_Receiver   `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Refund   *ManagedGPU_Refund     `protobuf:"bytes,2,opt,name=refund,proto3" json:"refund,omitempty"`
	// Required whenever the managed Governance receiver is configured.
	LwsAdmission  *ManagedGPU_LWSAdmission `protobuf:"bytes,3,opt,name=lws_admission,json=lwsAdmission,proto3" json:"lws_admission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedGPU) Reset() {
	*x = ManagedGPU{}
	mi := &file_inference_v1_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedGPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedGPU) ProtoMessage() {}

func (x *ManagedGPU) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedGPU.ProtoReflect.Descriptor instead.
func (*ManagedGPU) Descriptor() ([]byte, []int) {
	return file_inference_v1_conf_proto_rawDescGZIP(), []int{1}
}

func (x *ManagedGPU) GetReceiver() *ManagedGPU_Receiver {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *ManagedGPU) GetRefund() *ManagedGPU_Refund {
	if x != nil {
		return x.Refund
	}
	return nil
}

func (x *ManagedGPU) GetLwsAdmission() *ManagedGPU_LWSAdmission {
	if x != nil {
		return x.LwsAdmission
	}
	return nil
}

type Server struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Grpc            *Server_GRPC           `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Admin           *Server_Admin          `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	ShutdownTimeout *durationpb.Duration   `protobuf:"bytes,3,opt,name=shutdown_timeout,json=shutdownTimeout,proto3" json:"shutdown_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_inference_v1_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_inference_v1_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetAdmin() *Server_Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *Server) GetShutdownTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownTimeout
	}
	return nil
}

type ManagedGPU_Receiver struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	CaFile   string                 `protobuf:"bytes,1,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	CertFile string                 `protobuf:"bytes,2,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile  string                 `protobuf:"bytes,3,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	// Dedicated internal listener; the existing CPU/model-reference listener
	// retains its own transport contract.
	Address       string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedGPU_Receiver) Reset() {
	*x = ManagedGPU_Receiver{}
	mi := &file_inference_v1_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedGPU_Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedGPU_Receiver) ProtoMessage() {}

func (x *ManagedGPU_Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedGPU_Receiver.ProtoReflect.Descriptor instead.
func (*ManagedGPU_Receiver) Descriptor() ([]byte, []int) {
	return file_inference_v1_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ManagedGPU_Receiver) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

func (x *ManagedGPU_Receiver) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *ManagedGPU_Receiver) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *ManagedGPU_Receiver) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ManagedGPU_Refund struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	CaFile        string                 `protobuf:"bytes,2,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	CertFile      string                 `protobuf:"bytes,3,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile       string                 `protobuf:"bytes,4,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	ServerName    string                 `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedGPU_Refund) Reset() {
	*x = ManagedGPU_Refund{}
	mi := &file_inference_v1_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedGPU_Refund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedGPU_Refund) ProtoMessage() {}

func (x *ManagedGPU_Refund) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedGPU_Refund.ProtoReflect.Descriptor instead.
func (*ManagedGPU_Refund) Descriptor() ([]byte, []int) {
	return file_inference_v1_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ManagedGPU_Refund) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ManagedGPU_Refund) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

func (x *ManagedGPU_Refund) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *ManagedGPU_Refund) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *ManagedGPU_Refund) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ManagedGPU_Refund) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type ManagedGPU_LWSAdmission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Explicit TLS listener for synchronous managed LWS CREATE/UPDATE.
	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	CaFile   string `protobuf:"bytes,2,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	CertFile string `protobuf:"bytes,3,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile  string `protobuf:"bytes,4,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	// Exact single DNS SAN of the Kubernetes API server's client certificate.
	ApiServerClientDnsName string `protobuf:"bytes,5,opt,name=api_server_client_dns_name,json=apiServerClientDnsName,proto3" json:"api_server_client_dns_name,omitempty"`
	// Exact authenticated KServe controller service-account username.
	ControllerUsername string `protobuf:"bytes,6,opt,name=controller_username,json=controllerUsername,proto3" json:"controller_username,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ManagedGPU_LWSAdmission) Reset() {
	*x = ManagedGPU_LWSAdmission{}
	mi := &file_inference_v1_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedGPU_LWSAdmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedGPU_LWSAdmission) ProtoMessage() {}

func (x *ManagedGPU_LWSAdmission) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedGPU_LWSAdmission.ProtoReflect.Descriptor instead.
func (*ManagedGPU_LWSAdmission) Descriptor() ([]byte, []int) {
	return file_inference_v1_conf_proto_rawDescGZIP(), []int{1, 2}
}

func (x *ManagedGPU_LWSAdmission) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ManagedGPU_LWSAdmission) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

func (x *ManagedGPU_LWSAdmission) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *ManagedGPU_LWSAdmission) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *ManagedGPU_LWSAdmission) GetApiServerClientDnsName() string {
	if x != nil {
		return x.ApiServerClientDnsName
	}
	return ""
}

func (x *ManagedGPU_LWSAdmission) GetControllerUsername() string {
	if x != nil {
		return x.ControllerUsername
	}
	return ""
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_inference_v1_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_inference_v1_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_Admin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_Admin) Reset() {
	*x = Server_Admin{}
	mi := &file_inference_v1_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Admin) ProtoMessage() {}

func (x *Server_Admin) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Admin.ProtoReflect.Descriptor instead.
func (*Server_Admin) Descriptor() ([]byte, []int) {
	return file_inference_v1_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Server_Admin) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_Admin) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_Admin) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_inference_v1_conf_proto protoreflect.FileDescriptor

const file_inference_v1_conf_proto_rawDesc = "" +
	"\n" +
	"\x17inference/v1/conf.proto\x12\finference.v1\x1a\x1egoogle/protobuf/duration.proto\"t\n" +
	"\tBootstrap\x12,\n" +
	"\x06server\x18\x01 \x01(\v2\x14.inference.v1.ServerR\x06server\x129\n" +
	"\vmanaged_gpu\x18\x02 \x01(\v2\x18.inference.v1.ManagedGPUR\n" +
	"managedGpu\"\xfc\x05\n" +
	"\n" +
	"ManagedGPU\x12=\n" +
	"\breceiver\x18\x01 \x01(\v2!.inference.v1.ManagedGPU.ReceiverR\breceiver\x127\n" +
	"\x06refund\x18\x02 \x01(\v2\x1f.inference.v1.ManagedGPU.RefundR\x06refund\x12J\n" +
	"\rlws_admission\x18\x03 \x01(\v2%.inference.v1.ManagedGPU.LWSAdmissionR\flwsAdmission\x1au\n" +
	"\bReceiver\x12\x17\n" +
	"\aca_file\x18\x01 \x01(\tR\x06caFile\x12\x1b\n" +
	"\tcert_file\x18\x02 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x03 \x01(\tR\akeyFile\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x1a\xc9\x01\n" +
	"\x06Refund\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x17\n" +
	"\aca_file\x18\x02 \x01(\tR\x06caFile\x12\x1b\n" +
	"\tcert_file\x18\x03 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x04 \x01(\tR\akeyFile\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\x123\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1a\xe6\x01\n" +
	"\fLWSAdmission\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x17\n" +
	"\aca_file\x18\x02 \x01(\tR\x06caFile\x12\x1b\n" +
	"\tcert_file\x18\x03 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x04 \x01(\tR\akeyFile\x12:\n" +
	"\x1aapi_server_client_dns_name\x18\x05 \x01(\tR\x16apiServerClientDnsName\x12/\n" +
	"\x13controller_username\x18\x06 \x01(\tR\x12controllerUsername\"\x86\x03\n" +
	"\x06Server\x12-\n" +
	"\x04grpc\x18\x01 \x01(\v2\x19.inference.v1.Server.GRPCR\x04grpc\x120\n" +
	"\x05admin\x18\x02 \x01(\v2\x1a.inference.v1.Server.AdminR\x05admin\x12D\n" +
	"\x10shutdown_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0fshutdownTimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1aj\n" +
	"\x05Admin\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeoutBMZKgithub.com/zhangzhe-ctrl/ani-inference-service/api/inference/v1;inferencev1b\x06proto3"

var (
	file_inference_v1_conf_proto_rawDescOnce sync.Once
	file_inference_v1_conf_proto_rawDescData []byte
)

func file_inference_v1_conf_proto_rawDescGZIP() []byte {
	file_inference_v1_conf_proto_rawDescOnce.Do(func() {
		file_inference_v1_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_v1_conf_proto_rawDesc), len(file_inference_v1_conf_proto_rawDesc)))
	})
	return file_inference_v1_conf_proto_rawDescData
}

var file_inference_v1_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_inference_v1_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),               // 0: inference.v1.Bootstrap
	(*ManagedGPU)(nil),              // 1: inference.v1.ManagedGPU
	(*Server)(nil),                  // 2: inference.v1.Server
	(*ManagedGPU_Receiver)(nil),     // 3: inference.v1.ManagedGPU.Receiver
	(*ManagedGPU_Refund)(nil),       // 4: inference.v1.ManagedGPU.Refund
	(*ManagedGPU_LWSAdmission)(nil), // 5: inference.v1.ManagedGPU.LWSAdmission
	(*Server_GRPC)(nil),             // 6: inference.v1.Server.GRPC
	(*Server_Admin)(nil),            // 7: inference.v1.Server.Admin
	(*durationpb.Duration)(nil),     // 8: google.protobuf.Duration
}
var file_inference_v1_conf_proto_depIdxs = []int32{
	2,  // 0: inference.v1.Bootstrap.server:type_name -> inference.v1.Server
	1,  // 1: inference.v1.Bootstrap.managed_gpu:type_name -> inference.v1.ManagedGPU
	3,  // 2: inference.v1.ManagedGPU.receiver:type_name -> inference.v1.ManagedGPU.Receiver
	4,  // 3: inference.v1.ManagedGPU.refund:type_name -> inference.v1.ManagedGPU.Refund
	5,  // 4: inference.v1.ManagedGPU.lws_admission:type_name -> inference.v1.ManagedGPU.LWSAdmission
	6,  // 5: inference.v1.Server.grpc:type_name -> inference.v1.Server.GRPC
	7,  // 6: inference.v1.Server.admin:type_name -> inference.v1.Server.Admin
	8,  // 7: inference.v1.Server.shutdown_timeout:type_name -> google.protobuf.Duration
	8,  // 8: inference.v1.ManagedGPU.Refund.timeout:type_name -> google.protobuf.Duration
	8,  // 9: inference.v1.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	8,  // 10: inference.v1.Server.Admin.timeout:type_name -> google.protobuf.Duration
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_inference_v1_conf_proto_init() }
func file_inference_v1_conf_proto_init() {
	if File_inference_v1_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_v1_conf_proto_rawDesc), len(file_inference_v1_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inference_v1_conf_proto_goTypes,
		DependencyIndexes: file_inference_v1_conf_proto_depIdxs,
		MessageInfos:      file_inference_v1_conf_proto_msgTypes,
	}.Build()
	File_inference_v1_conf_proto = out.File
	file_inference_v1_conf_proto_goTypes = nil
	file_inference_v1_conf_proto_depIdxs = nil
}
