// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: inference/v1/inference.proto

package inferencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceServiceManager_CreateInferenceService_FullMethodName  = "/inference.v1.InferenceServiceManager/CreateInferenceService"
	InferenceServiceManager_GetInferenceService_FullMethodName     = "/inference.v1.InferenceServiceManager/GetInferenceService"
	InferenceServiceManager_ListInferenceServices_FullMethodName   = "/inference.v1.InferenceServiceManager/ListInferenceServices"
	InferenceServiceManager_UpdateInferenceService_FullMethodName  = "/inference.v1.InferenceServiceManager/UpdateInferenceService"
	InferenceServiceManager_StartInferenceService_FullMethodName   = "/inference.v1.InferenceServiceManager/StartInferenceService"
	InferenceServiceManager_StopInferenceService_FullMethodName    = "/inference.v1.InferenceServiceManager/StopInferenceService"
	InferenceServiceManager_RestartInferenceService_FullMethodName = "/inference.v1.InferenceServiceManager/RestartInferenceService"
	InferenceServiceManager_DeleteInferenceService_FullMethodName  = "/inference.v1.InferenceServiceManager/DeleteInferenceService"
	InferenceServiceManager_GetOperation_FullMethodName            = "/inference.v1.InferenceServiceManager/GetOperation"
	InferenceServiceManager_ListOperations_FullMethodName          = "/inference.v1.InferenceServiceManager/ListOperations"
)

// InferenceServiceManagerClient is the client API for InferenceServiceManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceServiceManagerClient interface {
	CreateInferenceService(ctx context.Context, in *CreateInferenceServiceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	GetInferenceService(ctx context.Context, in *GetInferenceServiceRequest, opts ...grpc.CallOption) (*InferenceService, error)
	ListInferenceServices(ctx context.Context, in *ListInferenceServicesRequest, opts ...grpc.CallOption) (*ListInferenceServicesResponse, error)
	UpdateInferenceService(ctx context.Context, in *UpdateInferenceServiceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	StartInferenceService(ctx context.Context, in *ServiceCommandRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	StopInferenceService(ctx context.Context, in *ServiceCommandRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	RestartInferenceService(ctx context.Context, in *ServiceCommandRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	DeleteInferenceService(ctx context.Context, in *DeleteInferenceServiceRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsResponse, error)
}

type inferenceServiceManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceServiceManagerClient(cc grpc.ClientConnInterface) InferenceServiceManagerClient {
	return &inferenceServiceManagerClient{cc}
}

func (c *inferenceServiceManagerClient) CreateInferenceService(ctx context.Context, in *CreateInferenceServiceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, InferenceServiceManager_CreateInferenceService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceManagerClient) GetInferenceService(ctx context.Context, in *GetInferenceServiceRequest, opts ...grpc.CallOption) (*InferenceService, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceService)
	err := c.cc.Invoke(ctx, InferenceServiceManager_GetInferenceService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceManagerClient) ListInferenceServices(ctx context.Context, in *ListInferenceServicesRequest, opts ...grpc.CallOption) (*ListInferenceServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInferenceServicesResponse)
	err := c.cc.Invoke(ctx, InferenceServiceManager_ListInferenceServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceManagerClient) UpdateInferenceService(ctx context.Context, in *UpdateInferenceServiceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, InferenceServiceManager_UpdateInferenceService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceManagerClient) StartInferenceService(ctx context.Context, in *ServiceCommandRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, InferenceServiceManager_StartInferenceService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceManagerClient) StopInferenceService(ctx context.Context, in *ServiceCommandRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, InferenceServiceManager_StopInferenceService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceManagerClient) RestartInferenceService(ctx context.Context, in *ServiceCommandRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, InferenceServiceManager_RestartInferenceService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceManagerClient) DeleteInferenceService(ctx context.Context, in *DeleteInferenceServiceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, InferenceServiceManager_DeleteInferenceService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceManagerClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, InferenceServiceManager_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceManagerClient) ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperationsResponse)
	err := c.cc.Invoke(ctx, InferenceServiceManager_ListOperations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceServiceManagerServer is the server API for InferenceServiceManager service.
// All implementations must embed UnimplementedInferenceServiceManagerServer
// for forward compatibility.
type InferenceServiceManagerServer interface {
	CreateInferenceService(context.Context, *CreateInferenceServiceRequest) (*OperationResponse, error)
	GetInferenceService(context.Context, *GetInferenceServiceRequest) (*InferenceService, error)
	ListInferenceServices(context.Context, *ListInferenceServicesRequest) (*ListInferenceServicesResponse, error)
	UpdateInferenceService(context.Context, *UpdateInferenceServiceRequest) (*OperationResponse, error)
	StartInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error)
	StopInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error)
	RestartInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error)
	DeleteInferenceService(context.Context, *DeleteInferenceServiceRequest) (*OperationResponse, error)
	GetOperation(context.Context, *GetOperationRequest) (*Operation, error)
	ListOperations(context.Context, *ListOperationsRequest) (*ListOperationsResponse, error)
	mustEmbedUnimplementedInferenceServiceManagerServer()
}

// UnimplementedInferenceServiceManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceServiceManagerServer struct{}

func (UnimplementedInferenceServiceManagerServer) CreateInferenceService(context.Context, *CreateInferenceServiceRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) GetInferenceService(context.Context, *GetInferenceServiceRequest) (*InferenceService, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) ListInferenceServices(context.Context, *ListInferenceServicesRequest) (*ListInferenceServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInferenceServices not implemented")
}
func (UnimplementedInferenceServiceManagerServer) UpdateInferenceService(context.Context, *UpdateInferenceServiceRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) StartInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) StopInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) RestartInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) DeleteInferenceService(context.Context, *DeleteInferenceServiceRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) GetOperation(context.Context, *GetOperationRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedInferenceServiceManagerServer) ListOperations(context.Context, *ListOperationsRequest) (*ListOperationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOperations not implemented")
}
func (UnimplementedInferenceServiceManagerServer) mustEmbedUnimplementedInferenceServiceManagerServer() {
}
func (UnimplementedInferenceServiceManagerServer) testEmbeddedByValue() {}

// UnsafeInferenceServiceManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServiceManagerServer will
// result in compilation errors.
type UnsafeInferenceServiceManagerServer interface {
	mustEmbedUnimplementedInferenceServiceManagerServer()
}

func RegisterInferenceServiceManagerServer(s grpc.ServiceRegistrar, srv InferenceServiceManagerServer) {
	// If the following call panics, it indicates UnimplementedInferenceServiceManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceServiceManager_ServiceDesc, srv)
}

func _InferenceServiceManager_CreateInferenceService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInferenceServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).CreateInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceServiceManager_CreateInferenceService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceManagerServer).CreateInferenceService(ctx, req.(*CreateInferenceServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceServiceManager_GetInferenceService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInferenceServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).GetInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceServiceManager_GetInferenceService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceManagerServer).GetInferenceService(ctx, req.(*GetInferenceServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceServiceManager_ListInferenceServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInferenceServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).ListInferenceServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceServiceManager_ListInferenceServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceManagerServer).ListInferenceServices(ctx, req.(*ListInferenceServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceServiceManager_UpdateInferenceService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInferenceServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).UpdateInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceServiceManager_UpdateInferenceService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceManagerServer).UpdateInferenceService(ctx, req.(*UpdateInferenceServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceServiceManager_StartInferenceService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).StartInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceServiceManager_StartInferenceService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceManagerServer).StartInferenceService(ctx, req.(*ServiceCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceServiceManager_StopInferenceService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).StopInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceServiceManager_StopInferenceService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceManagerServer).StopInferenceService(ctx, req.(*ServiceCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceServiceManager_RestartInferenceService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).RestartInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceServiceManager_RestartInferenceService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceManagerServer).RestartInferenceService(ctx, req.(*ServiceCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceServiceManager_DeleteInferenceService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInferenceServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).DeleteInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceServiceManager_DeleteInferenceService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceManagerServer).DeleteInferenceService(ctx, req.(*DeleteInferenceServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceServiceManager_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceServiceManager_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceManagerServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceServiceManager_ListOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).ListOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceServiceManager_ListOperations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceManagerServer).ListOperations(ctx, req.(*ListOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceServiceManager_ServiceDesc is the grpc.ServiceDesc for InferenceServiceManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceServiceManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.v1.InferenceServiceManager",
	HandlerType: (*InferenceServiceManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInferenceService",
			Handler:    _InferenceServiceManager_CreateInferenceService_Handler,
		},
		{
			MethodName: "GetInferenceService",
			Handler:    _InferenceServiceManager_GetInferenceService_Handler,
		},
		{
			MethodName: "ListInferenceServices",
			Handler:    _InferenceServiceManager_ListInferenceServices_Handler,
		},
		{
			MethodName: "UpdateInferenceService",
			Handler:    _InferenceServiceManager_UpdateInferenceService_Handler,
		},
		{
			MethodName: "StartInferenceService",
			Handler:    _InferenceServiceManager_StartInferenceService_Handler,
		},
		{
			MethodName: "StopInferenceService",
			Handler:    _InferenceServiceManager_StopInferenceService_Handler,
		},
		{
			MethodName: "RestartInferenceService",
			Handler:    _InferenceServiceManager_RestartInferenceService_Handler,
		},
		{
			MethodName: "DeleteInferenceService",
			Handler:    _InferenceServiceManager_DeleteInferenceService_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _InferenceServiceManager_GetOperation_Handler,
		},
		{
			MethodName: "ListOperations",
			Handler:    _InferenceServiceManager_ListOperations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inference/v1/inference.proto",
}
