// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: managed_gpu.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getManagedGPUCommand = `-- name: GetManagedGPUCommand :one
SELECT tenant_id, operation_id, resource_id, create_operation_id, kind, payload_hash, request_hash, command_payload, response_snapshot, durable_ack, execution_intent, created_at FROM inference_managed_gpu_commands
WHERE tenant_id = $1 AND operation_id = $2
`

type GetManagedGPUCommandParams struct {
	TenantID    pgtype.UUID
	OperationID pgtype.UUID
}

func (q *Queries) GetManagedGPUCommand(ctx context.Context, arg GetManagedGPUCommandParams) (InferenceManagedGpuCommand, error) {
	row := q.db.QueryRow(ctx, getManagedGPUCommand, arg.TenantID, arg.OperationID)
	var i InferenceManagedGpuCommand
	err := row.Scan(
		&i.TenantID,
		&i.OperationID,
		&i.ResourceID,
		&i.CreateOperationID,
		&i.Kind,
		&i.PayloadHash,
		&i.RequestHash,
		&i.CommandPayload,
		&i.ResponseSnapshot,
		&i.DurableAck,
		&i.ExecutionIntent,
		&i.CreatedAt,
	)
	return i, err
}

const getManagedGPURefundContext = `-- name: GetManagedGPURefundContext :one
SELECT original_context,delete_operation_id FROM inference_managed_gpu_resources
WHERE tenant_id=$1 AND resource_id=$2 AND create_operation_id=$3
`

type GetManagedGPURefundContextParams struct {
	TenantID          pgtype.UUID
	ResourceID        pgtype.UUID
	CreateOperationID pgtype.UUID
}

type GetManagedGPURefundContextRow struct {
	OriginalContext   []byte
	DeleteOperationID pgtype.UUID
}

func (q *Queries) GetManagedGPURefundContext(ctx context.Context, arg GetManagedGPURefundContextParams) (GetManagedGPURefundContextRow, error) {
	row := q.db.QueryRow(ctx, getManagedGPURefundContext, arg.TenantID, arg.ResourceID, arg.CreateOperationID)
	var i GetManagedGPURefundContextRow
	err := row.Scan(&i.OriginalContext, &i.DeleteOperationID)
	return i, err
}

const getManagedGPUResource = `-- name: GetManagedGPUResource :one
SELECT tenant_id, resource_id, create_operation_id, owner_service, metering_version, original_context, business_payload, business_payload_digest, create_request_hash, create_payload, delete_operation_id, closing, created_at, updated_at FROM inference_managed_gpu_resources
WHERE tenant_id = $1 AND resource_id = $2
`

type GetManagedGPUResourceParams struct {
	TenantID   pgtype.UUID
	ResourceID pgtype.UUID
}

func (q *Queries) GetManagedGPUResource(ctx context.Context, arg GetManagedGPUResourceParams) (InferenceManagedGpuResource, error) {
	row := q.db.QueryRow(ctx, getManagedGPUResource, arg.TenantID, arg.ResourceID)
	var i InferenceManagedGpuResource
	err := row.Scan(
		&i.TenantID,
		&i.ResourceID,
		&i.CreateOperationID,
		&i.OwnerService,
		&i.MeteringVersion,
		&i.OriginalContext,
		&i.BusinessPayload,
		&i.BusinessPayloadDigest,
		&i.CreateRequestHash,
		&i.CreatePayload,
		&i.DeleteOperationID,
		&i.Closing,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagedGPUResourceForUpdate = `-- name: GetManagedGPUResourceForUpdate :one
SELECT tenant_id, resource_id, create_operation_id, owner_service, metering_version, original_context, business_payload, business_payload_digest, create_request_hash, create_payload, delete_operation_id, closing, created_at, updated_at FROM inference_managed_gpu_resources
WHERE tenant_id = $1 AND resource_id = $2 FOR UPDATE
`

type GetManagedGPUResourceForUpdateParams struct {
	TenantID   pgtype.UUID
	ResourceID pgtype.UUID
}

func (q *Queries) GetManagedGPUResourceForUpdate(ctx context.Context, arg GetManagedGPUResourceForUpdateParams) (InferenceManagedGpuResource, error) {
	row := q.db.QueryRow(ctx, getManagedGPUResourceForUpdate, arg.TenantID, arg.ResourceID)
	var i InferenceManagedGpuResource
	err := row.Scan(
		&i.TenantID,
		&i.ResourceID,
		&i.CreateOperationID,
		&i.OwnerService,
		&i.MeteringVersion,
		&i.OriginalContext,
		&i.BusinessPayload,
		&i.BusinessPayloadDigest,
		&i.CreateRequestHash,
		&i.CreatePayload,
		&i.DeleteOperationID,
		&i.Closing,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagedGPUState = `-- name: GetManagedGPUState :one
SELECT EXISTS(SELECT 1 FROM inference_managed_gpu_resources AS managed_resource WHERE managed_resource.tenant_id=$1 AND managed_resource.resource_id=$2) AS managed,
       EXISTS(SELECT 1 FROM inference_managed_gpu_resources AS closing_resource WHERE closing_resource.tenant_id=$1 AND closing_resource.resource_id=$2 AND closing_resource.closing) AS closing
`

type GetManagedGPUStateParams struct {
	TenantID   pgtype.UUID
	ResourceID pgtype.UUID
}

type GetManagedGPUStateRow struct {
	Managed bool
	Closing bool
}

func (q *Queries) GetManagedGPUState(ctx context.Context, arg GetManagedGPUStateParams) (GetManagedGPUStateRow, error) {
	row := q.db.QueryRow(ctx, getManagedGPUState, arg.TenantID, arg.ResourceID)
	var i GetManagedGPUStateRow
	err := row.Scan(&i.Managed, &i.Closing)
	return i, err
}

const insertManagedGPUCommand = `-- name: InsertManagedGPUCommand :exec
INSERT INTO inference_managed_gpu_commands(tenant_id,operation_id,resource_id,create_operation_id,kind,payload_hash,request_hash,command_payload,response_snapshot,durable_ack,execution_intent)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type InsertManagedGPUCommandParams struct {
	TenantID          pgtype.UUID
	OperationID       pgtype.UUID
	ResourceID        pgtype.UUID
	CreateOperationID pgtype.UUID
	Kind              string
	PayloadHash       string
	RequestHash       string
	CommandPayload    []byte
	ResponseSnapshot  []byte
	DurableAck        []byte
	ExecutionIntent   string
}

func (q *Queries) InsertManagedGPUCommand(ctx context.Context, arg InsertManagedGPUCommandParams) error {
	_, err := q.db.Exec(ctx, insertManagedGPUCommand,
		arg.TenantID,
		arg.OperationID,
		arg.ResourceID,
		arg.CreateOperationID,
		arg.Kind,
		arg.PayloadHash,
		arg.RequestHash,
		arg.CommandPayload,
		arg.ResponseSnapshot,
		arg.DurableAck,
		arg.ExecutionIntent,
	)
	return err
}

const insertManagedGPUResource = `-- name: InsertManagedGPUResource :exec
INSERT INTO inference_managed_gpu_resources(tenant_id,resource_id,create_operation_id,owner_service,metering_version,original_context)
VALUES($1,$2,$3,$4,$5,$6)
`

type InsertManagedGPUResourceParams struct {
	TenantID          pgtype.UUID
	ResourceID        pgtype.UUID
	CreateOperationID pgtype.UUID
	OwnerService      string
	MeteringVersion   string
	OriginalContext   []byte
}

func (q *Queries) InsertManagedGPUResource(ctx context.Context, arg InsertManagedGPUResourceParams) error {
	_, err := q.db.Exec(ctx, insertManagedGPUResource,
		arg.TenantID,
		arg.ResourceID,
		arg.CreateOperationID,
		arg.OwnerService,
		arg.MeteringVersion,
		arg.OriginalContext,
	)
	return err
}

const lockManagedGPUKey = `-- name: LockManagedGPUKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockManagedGPUKey(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, lockManagedGPUKey, lockKey)
	return err
}

const managedGPUServiceExists = `-- name: ManagedGPUServiceExists :one
SELECT EXISTS(SELECT 1 FROM inference_services WHERE tenant_id=$1 AND id=$2)
`

type ManagedGPUServiceExistsParams struct {
	TenantID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) ManagedGPUServiceExists(ctx context.Context, arg ManagedGPUServiceExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, managedGPUServiceExists, arg.TenantID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const saveManagedGPUCreate = `-- name: SaveManagedGPUCreate :exec
UPDATE inference_managed_gpu_resources
SET business_payload=$1,business_payload_digest=$2,
    create_request_hash=$3,create_payload=$4,updated_at=now()
WHERE tenant_id=$5 AND resource_id=$6 AND create_payload IS NULL
`

type SaveManagedGPUCreateParams struct {
	BusinessPayload       []byte
	BusinessPayloadDigest string
	CreateRequestHash     string
	CreatePayload         []byte
	TenantID              pgtype.UUID
	ResourceID            pgtype.UUID
}

func (q *Queries) SaveManagedGPUCreate(ctx context.Context, arg SaveManagedGPUCreateParams) error {
	_, err := q.db.Exec(ctx, saveManagedGPUCreate,
		arg.BusinessPayload,
		arg.BusinessPayloadDigest,
		arg.CreateRequestHash,
		arg.CreatePayload,
		arg.TenantID,
		arg.ResourceID,
	)
	return err
}

const setManagedGPUClosing = `-- name: SetManagedGPUClosing :exec
UPDATE inference_managed_gpu_resources
SET closing=TRUE,delete_operation_id=COALESCE(delete_operation_id,$1::uuid),updated_at=now()
WHERE tenant_id=$2 AND resource_id=$3
`

type SetManagedGPUClosingParams struct {
	DeleteOperationID pgtype.UUID
	TenantID          pgtype.UUID
	ResourceID        pgtype.UUID
}

func (q *Queries) SetManagedGPUClosing(ctx context.Context, arg SetManagedGPUClosingParams) error {
	_, err := q.db.Exec(ctx, setManagedGPUClosing, arg.DeleteOperationID, arg.TenantID, arg.ResourceID)
	return err
}
