// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: managed_lws.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasManagedLWSOwnerCandidate = `-- name: HasManagedLWSOwnerCandidate :one
SELECT EXISTS(
  SELECT 1 FROM inference_managed_gpu_resources m
  LEFT JOIN inference_services s ON s.tenant_id=m.tenant_id AND s.id=m.resource_id
  WHERE s.name=$1 OR m.business_payload->>'name'=$1
)
`

// A matching accepted name without the observed UID binding is pending, not
// permission to let an unprojected first CREATE through. Closing tombstones
// with saved CREATE business also remain protected.
func (q *Queries) HasManagedLWSOwnerCandidate(ctx context.Context, objectName string) (bool, error) {
	row := q.db.QueryRow(ctx, hasManagedLWSOwnerCandidate, objectName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listManagedLWSOwnerBindings = `-- name: ListManagedLWSOwnerBindings :many
SELECT DISTINCT ON (b.tenant_id,b.service_id)
       b.tenant_id,b.service_id,b.generation,b.object_kind,b.object_namespace,
       b.object_name,b.object_uid,b.resource_version,b.role,
       s.desired_generation,m.original_context,m.closing
FROM inference_runtime_bindings b
JOIN inference_services s ON s.tenant_id=b.tenant_id AND s.id=b.service_id
JOIN inference_specs sp ON sp.tenant_id=s.tenant_id AND sp.service_id=s.id AND sp.generation=s.desired_generation
JOIN inference_managed_gpu_resources m ON m.tenant_id=s.tenant_id AND m.resource_id=s.id
WHERE b.object_namespace=$1 AND b.object_name=$2
  AND b.object_uid=$3 AND b.object_kind='KServeLLMInferenceService' AND b.role='runtime'
  AND b.generation<=s.desired_generation AND s.deleted_at IS NULL
  AND sp.runtime_provider='kserve' AND sp.runtime_mode='leader_worker_set'
ORDER BY b.tenant_id,b.service_id,b.generation DESC
`

type ListManagedLWSOwnerBindingsParams struct {
	ObjectNamespace string
	ObjectName      string
	ObjectUid       string
}

type ListManagedLWSOwnerBindingsRow struct {
	TenantID          pgtype.UUID
	ServiceID         pgtype.UUID
	Generation        int64
	ObjectKind        string
	ObjectNamespace   string
	ObjectName        string
	ObjectUid         string
	ResourceVersion   string
	Role              string
	DesiredGeneration int64
	OriginalContext   []byte
	Closing           bool
}

// Namespace/name/UID is an observed Kubernetes object identity. Tenant and
// service scope come from this binding, never from admission object labels.
func (q *Queries) ListManagedLWSOwnerBindings(ctx context.Context, arg ListManagedLWSOwnerBindingsParams) ([]ListManagedLWSOwnerBindingsRow, error) {
	rows, err := q.db.Query(ctx, listManagedLWSOwnerBindings, arg.ObjectNamespace, arg.ObjectName, arg.ObjectUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagedLWSOwnerBindingsRow
	for rows.Next() {
		var i ListManagedLWSOwnerBindingsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ServiceID,
			&i.Generation,
			&i.ObjectKind,
			&i.ObjectNamespace,
			&i.ObjectName,
			&i.ObjectUid,
			&i.ResourceVersion,
			&i.Role,
			&i.DesiredGeneration,
			&i.OriginalContext,
			&i.Closing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
