// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InferenceAuditEvent struct {
	TenantID    pgtype.UUID
	EventID     pgtype.UUID
	ServiceID   pgtype.UUID
	OperationID pgtype.UUID
	Generation  int64
	EventType   string
	Actor       string
	RequestID   string
	BeforeState []byte
	AfterState  []byte
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
}

type InferenceIdempotencyRequest struct {
	TenantID       pgtype.UUID
	Method         string
	IdempotencyKey string
	PayloadHash    string
	OperationID    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type InferenceManagedGpuCommand struct {
	TenantID          pgtype.UUID
	OperationID       pgtype.UUID
	ResourceID        pgtype.UUID
	CreateOperationID pgtype.UUID
	Kind              string
	PayloadHash       string
	RequestHash       string
	CommandPayload    []byte
	ResponseSnapshot  []byte
	DurableAck        []byte
	ExecutionIntent   string
	CreatedAt         pgtype.Timestamptz
}

type InferenceManagedGpuResource struct {
	TenantID              pgtype.UUID
	ResourceID            pgtype.UUID
	CreateOperationID     pgtype.UUID
	OwnerService          string
	MeteringVersion       string
	OriginalContext       []byte
	BusinessPayload       []byte
	BusinessPayloadDigest string
	CreateRequestHash     string
	CreatePayload         []byte
	DeleteOperationID     pgtype.UUID
	Closing               bool
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type InferenceObservationEvent struct {
	TenantID              pgtype.UUID
	EventID               pgtype.UUID
	ServiceID             pgtype.UUID
	Generation            int64
	SourceKind            string
	SourceUid             string
	SourceResourceVersion string
	ObservedAt            pgtype.Timestamptz
	Payload               []byte
}

type InferenceOperation struct {
	TenantID         pgtype.UUID
	ID               pgtype.UUID
	ServiceID        pgtype.UUID
	Kind             string
	Phase            string
	Step             string
	TargetGeneration int64
	RequestHash      string
	Attempt          int32
	RetryAt          pgtype.Timestamptz
	LeaseOwner       pgtype.Text
	LeaseUntil       pgtype.Timestamptz
	LeaseToken       pgtype.UUID
	ErrorCode        string
	ErrorMessage     string
	ResultSnapshot   []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
}

type InferencePublication struct {
	TenantID             pgtype.UUID
	ServiceID            pgtype.UUID
	Generation           int64
	DesiredPhase         string
	ObservedPhase        string
	InvocationUrl        string
	OwnedKind            string
	OwnedNamespace       string
	OwnedName            string
	OwnedUid             string
	OwnedResourceVersion string
	LastErrorCode        string
	ObservedAt           pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type InferenceQuotaReservation struct {
	TenantID           pgtype.UUID
	ServiceID          pgtype.UUID
	OperationID        pgtype.UUID
	Generation         int64
	ReservationID      string
	RequestedResources []byte
	State              string
	LastErrorCode      string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type InferenceResourceWork struct {
	TenantID            pgtype.UUID
	ServiceID           pgtype.UUID
	DirtyVersion        int64
	AcknowledgedVersion int64
	NextRunAt           pgtype.Timestamptz
	Attempt             int32
	LeaseOwner          pgtype.Text
	LeaseUntil          pgtype.Timestamptz
	LeaseToken          pgtype.UUID
	LastErrorCode       string
	UpdatedAt           pgtype.Timestamptz
}

type InferenceRuntime struct {
	TenantID                  pgtype.UUID
	ServiceID                 pgtype.UUID
	Generation                int64
	CrUid                     string
	DeploymentUid             string
	ServiceUid                string
	DeploymentResourceVersion pgtype.Text
	RuntimePhase              string
	ReadyReplicas             int32
	ModelReady                bool
	PublicationPhase          string
	InvocationHealth          string
	RuntimeEndpoint           string
	ObservedAt                pgtype.Timestamptz
	StaleAfter                pgtype.Timestamptz
	Reason                    string
	UpdatedAt                 pgtype.Timestamptz
	RuntimeMode               string
	ReadyGroups               int32
	ReadyWorkers              int32
	LwsUid                    string
	ModelReadyKnown           bool
}

type InferenceRuntimeBinding struct {
	TenantID        pgtype.UUID
	ServiceID       pgtype.UUID
	Generation      int64
	ObjectKind      string
	ObjectNamespace string
	ObjectName      string
	ObjectUid       string
	ResourceVersion string
	Role            string
	ObservedAt      pgtype.Timestamptz
}

type InferenceService struct {
	TenantID           pgtype.UUID
	ID                 pgtype.UUID
	Name               string
	DesiredState       string
	DesiredGeneration  int64
	CurrentOperationID pgtype.UUID
	DeletedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	AppliedGeneration  int64
}

type InferenceSpec struct {
	TenantID              pgtype.UUID
	ID                    pgtype.UUID
	ServiceID             pgtype.UUID
	Generation            int64
	ModelID               pgtype.UUID
	ModelVersionID        pgtype.UUID
	ArtifactProvider      string
	ArtifactRef           string
	ArtifactSha256        string
	ImageRef              string
	ServedModelName       string
	EngineRuntime         string
	CommandArgv           []byte
	Resources             []byte
	Replicas              int32
	SpecJson              []byte
	CreatedAt             pgtype.Timestamptz
	RuntimeMode           string
	WorkerReplicas        int32
	EndpointContainerPort pgtype.Int4
	EndpointServicePort   pgtype.Int4
	EndpointTargetPort    pgtype.Text
	EndpointProtocol      pgtype.Text
	RuntimeProvider       string
	// Frozen GPU request; a record absent from inference_managed_gpu_resources is legacy direct, not eligible for Governance refund
	GpuRequest    []byte
	GpuPlan       []byte
	GpuPlanDigest pgtype.Text
}
